DROP TRIGGER IF EXISTS projetos_BEFORE_INSERT;
DROP TRIGGER IF EXISTS projetos_BEFORE_UPDATE;
DROP TRIGGER IF EXISTS categorias_docentes_BEFORE_INSERT;
DROP TRIGGER IF EXISTS categorias_docentes_BEFORE_UPDATE;

DROP PROCEDURE IF EXISTS `get_vinculos_by_codigo`;
